# Generated by Django 3.0.5 on 2020-05-05 00:26

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='post',
            name='images',
            field=models.ManyToManyField(through='blog.PostImage', to='blog.Image'),
        ),
        migrations.AlterUniqueTogether(
            name='postcategory',
            unique_together={('post_id', 'category_id')},
        ),
        migrations.AlterUniqueTogether(
            name='postimage',
            unique_together={('post_id', 'image_id')},
        ),
    ]
