version: "3.2"
services:
  # Service 2
  frontend:
    container_name: frontend
    build: ../frontend
    volumes:
      - ../frontend:/usr/src/frontend
    ports:
      - "3000:3000"
    command: npm run dev
  # Service 3
  backend:
    container_name: backend
    build: ../backend
    volumes:
      - ../backend:/usr/src/backend
    ports:
      - "8000:8000"
    stdin_open: true
    tty: true
    command: "python3 manage.py runserver 0.0.0.0:8000"
  # Service 4
  nginx:
    container_name: nginx
    build: ../nginx
    volumes:
      - ../nginx/conf.d/:/etc/nginx/conf.d
    ports:
      - "80:80"
